In [4]:
#1
sqr = lambda x: x ** 2

square = float(input("Enter a number : "))
result = sqr(square)
print(f"The square of {square} is {result}.")

Enter a number :  6


The square of 6.0 is 36.0.


In [3]:
# numpy 1
import numpy as np
print(np.zeros([3,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
#2
import numpy as np
print(np.ones([2,5]))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
#3
import numpy as np
print(np.arange(1,11))


[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#4
import numpy as np
print(np.arange(0,1.1,0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [10]:
#5
import numpy as np
print(np.linspace(0, 1, 10, endpoint=False))




[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [13]:
#6
import numpy as np


arr=np.array([1, 4, 9, 16])
print(np.sqrt(arr) )




[1. 2. 3. 4.]


In [22]:
#7
import numpy as np

arr= np.array([2, 3, 4, 5, 6])


print(np.sum(arr)) 



20


In [21]:
#8
import numpy as np
arr= np.array([1, 5, 9, 3, 6])
print(np.min(arr))


1


In [24]:
#9
import numpy as np
arr = np.array([1, 5, 9, 3, 6])
print(np.max(arr))


9


In [27]:
#11
import numpy as np
arr = np.random.randint(10, 50, size=5)

print(arr)


[32 40 23 29 31]


In [28]:
#python question 15
def grade(marks):
    if marks >= 90:
        return "Grade A"
    elif marks >= 75:
        return "Grade B"
    elif marks >= 50:
        return "Grade C"
    else:
        return "Grade F"
marks = float(input("Enter  marks: "))
grade = grade(marks)
print("The student's grade is:", grade)


Enter  marks:  45


The student's grade is: Grade F


In [30]:
#17
def max_of_three(a, b, c):
    return max(a, b, c)

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))
max_number = max_of_three(num1, num2, num3)
print(max_number)


 


Enter the first number:  2
Enter the second number:  45
Enter the third number:  77


77.0
